# This code was generated by chatGPT

from colorama import init, Fore, Style
init()

while True:
    key = input("Type something. Press q to quit.\n")
    if key == 'q':
        break

    colored_text = ''
    for i, c in enumerate(key):
        if i % 3 == 0:
            colored_text += Fore.RED + c
        elif i % 3 == 1:
            colored_text += Fore.GREEN + c
        elif i % 3 == 2:
            colored_text += Fore.YELLOW + c

    print(colored_text + Style.RESET_ALL)
